[window]
decorations = "Buttonless"
dynamic_padding = false
dynamic_title = false
startup_mode = "Windowed"
opacity = 0.86
blur = true

# Catppuccin
# https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-mocha.toml
[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"
[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"
[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"
[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"
[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"
[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"
[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"
[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"
[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"
[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"
[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"
[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"
[[colors.indexed_colors]]
index = 16
color = "#FAB387"
[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

# Monokai Dark
# https://unpkg.com/browse/alacritty-themes@4.1.5/themes/Monokai.dark.yml
# [colors.primary]
# background = "#171812"
# foreground = "#f8f8f2"
# [colors.cursor]
# text = "#272822"
# cursor = "#f8f8f2"
# [colors.normal]
# black = "#272822"
# red = "#f92672"
# green = "#a6e22e"
# yellow = "#f4bf75"
# blue = "#66d9ef"
# magenta = "#ae81ff"
# cyan = "#a1efe4"
# white = "#f8f8f2"
# [colors.bright]
# black = "#75715e"
# red = "#f92672"
# green = "#a6e22e"
# yellow = "#f4bf75"
# blue = "#66d9ef"
# magenta = "#ae81ff"
# cyan = "#a1efe4"
# white = "#f9f8f5"

# Monokai Pro
# https://unpkg.com/browse/alacritty-themes@4.1.5/themes/Monokai-Pro.yml
# [colors.primary]
# background ="#1D1A1E"
# foreground ="#FCFCFA" 
# [colors.cursor]
# text = "#272822"
# cursor = "#f8f8f2"
# [colors.normal]
# black ="#403E41"
# red ="#FF6188"
# green ="#A9DC76"
# yellow ="#FFD866"
# blue ="#FC9867"
# magenta ="#AB9DF2"
# cyan ="#78DCE8"
# white ="#FCFCFA"
# [colors.bright]
# black ="#727072"
# red ="#FF6188"
# green ="#A9DC76"
# yellow ="#FFD866"
# blue ="#FC9867"
# magenta ="#AB9DF2"
# cyan ="#78DCE8"
# white ="#FCFCFA"


# Monokai Soda
# https://unpkg.com/browse/alacritty-themes@4.1.5/themes/Monokai-Soda.yml
# [colors.primary]
# background = "#1a1a1a"
# foreground = "#c4c5b5"
# [colors.cursor]
# text = "#272822"
# cursor = "#f8f8f2"
# [colors.normal]
# black = "#1a1a1a"
# red = "#f4005f"
# green = "#98e024"
# yellow = "#fa8419"
# blue = "#9d65ff"
# magenta = "#f4005f"
# cyan = "#58d1eb"
# white = "#c4c5b5"
# [colors.bright]
# black = "#625e4c"
# red = "#f4005f"
# green = "#98e024"
# yellow = "#e0d561"
# blue = "#9d65ff"
# magenta = "#f4005f"
# cyan = "#58d1eb"
# white = "#f6f6ef"



[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = 36
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\\x0c"
key = "L"
mods = "Control"


[scrolling]
history = 10000

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 8
y = 8
